# Generated by Django 4.1.3 on 2022-11-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alta_turnos',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('mensaje', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('asunto', models.CharField(max_length=30)),
                ('mensaje', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='monitoreodepeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('pesoinicial', models.CharField(max_length=30)),
                ('pesoactual', models.CharField(max_length=30)),
                ('pesodeseado', models.CharField(max_length=30)),
                ('fecha', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='sigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
