# Generated by Django 4.2 on 2023-05-17 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(default='DEFAULT_VALUE', max_length=8)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(default=datetime.time(0, 7, 13, 604059))),
                ('mensaje', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField(auto_now=True)),
            ],
        ),
    ]
