# Generated by Django 4.2 on 2023-06-16 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(default='DEFAULT_VALUE', max_length=8)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(default=datetime.time(21, 21, 23, 220727))),
                ('mensaje', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateField(auto_now=True)),
                ('last_login', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
